# Generated by Django 5.2.1 on 2025-05-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shape',
            new_name='Label',
        ),
    ]
