# Generated by Django 5.2.1 on 2025-05-14 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_rename_shape_label'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Label',
            new_name='FrontLabel',
        ),
    ]
