# Generated by Django 5.2.1 on 2025-05-14 14:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_rename_label_frontlabel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trolley',
            old_name='date_added',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='frontlabel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trolley',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='BackLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.IntegerField(choices=[(1, 'Square'), (2, 'Circle'), (3, 'Triangle'), (4, 'Cross'), (5, 'Squiggle'), (6, 'Heart'), (7, 'Flower'), (8, 'Penguin'), (9, 'Bowtie'), (10, 'Airplane')], default=1)),
                ('checked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trolley', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.trolley')),
            ],
        ),
    ]
